name: UniverseCore
version: '${project.version}'
main: space.yurisi.universecore.UniverseCore
api-version: '1.20'
commands:
  password:
    description: パスワードを設定します
    usage: /password <password 大文字小文字数字含む8~36文字>