use SpaceServerUniverse;

CREATE TABLE IF NOT EXISTS gacha_info(
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    gacha_name VARCHAR(40) NOT NULL,
    gacha_description VARCHAR(255) NOT NULL,
    price BIGINT UNSIGNED NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL
);

CREATE TABLE IF NOT EXISTS gacha_content(
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    gacha_id BIGINT UNSIGNED NOT NULL,
    gacha_item_id BIGINT UNSIGNED NOT NULL,
    rarelity BIGINT UNSIGNED NOT NULL,
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL
);

CREATE TABLE IF NOT EXISTS gacha_item(
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    item_id BIGINT UNSIGNED NOT NULL,
    item_name VARCHAR(40) NOT NULL,
    item_amount BIGINT UNSIGNED NOT NULL DEFAULT 1,
    enchantment VARCHAR(27) NOT NULL,
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL
);